/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IntersectionObserverSentinel {
        "block": boolean;
        "configOptions": object;
        "enterCallback": Function;
        "exitCallback": Function;
        "hostClass": string;
        "hostId": string;
        "sentinelClass": string;
        "sentinelId": string;
    }
}
declare global {
    interface HTMLIntersectionObserverSentinelElement extends Components.IntersectionObserverSentinel, HTMLStencilElement {
    }
    var HTMLIntersectionObserverSentinelElement: {
        prototype: HTMLIntersectionObserverSentinelElement;
        new (): HTMLIntersectionObserverSentinelElement;
    };
    interface HTMLElementTagNameMap {
        "intersection-observer-sentinel": HTMLIntersectionObserverSentinelElement;
    }
}
declare namespace LocalJSX {
    interface IntersectionObserverSentinel {
        "block"?: boolean;
        "configOptions"?: object;
        "enterCallback"?: Function;
        "exitCallback"?: Function;
        "hostClass"?: string;
        "hostId"?: string;
        "sentinelClass"?: string;
        "sentinelId"?: string;
    }
    interface IntrinsicElements {
        "intersection-observer-sentinel": IntersectionObserverSentinel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "intersection-observer-sentinel": LocalJSX.IntersectionObserverSentinel & JSXBase.HTMLAttributes<HTMLIntersectionObserverSentinelElement>;
        }
    }
}
